AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  cloud-watch-create-metrics

  Sample SAM Template for cloud-watch-create-metrics

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20

Resources:
  CreateMetricsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: CreateMetricsFunction
      Handler: metrics.App::handleRequest
      Runtime: java8
      MemorySize: 512
      Role: arn:aws:iam::494526681395:role/for-aws-training-2
  ScheduledRule:
    Type: AWS::Events::Rule
    Properties:
      ScheduleExpression: "rate(1 minute)"
      State: "ENABLED"
      Targets:
        - Arn:
            Fn::GetAtt:
              - "CreateMetricsFunction"
              - "Arn"
          Id: "TargetFunctionV1"
  PermissionForEventsToInvokeLambda:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName:
        Ref: "CreateMetricsFunction"
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn:
        Fn::GetAtt:
          - "ScheduledRule"
          - "Arn"
  MySNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Endpoint:
            Fn::GetAtt:
              - "MyQueue1"
              - "Arn"
          Protocol: "sqs"
        - Endpoint:
            Fn::GetAtt:
              - "MyQueue2"
              - "Arn"
          Protocol: "sqs"
      TopicName: "SampleTopic"
  PageVisitedAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: page visited invocations
      AlarmName: PageVisitedAlarm

      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 1
      Dimensions:
        - Name: "UNIQUE_PAGES"
          Value: "URLS"
      MetricName: "PAGES_VISITED"
      Namespace: "SITE/TRAFFIC"
      Threshold: 1
      TreatMissingData: breaching
      "AlarmActions": [
        - Fn::GetAtt:
            - "ScheduledRule"
            - "Arn",
        - "arn:aws:sns:region:account-id:sns-topic-name"
      ],


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  CreateMetricsFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt CreateMetricsFunction.Arn
