---
version: '2.3'
services:
  database:
    image: "postgres:11.1-alpine"
    environment:
      POSTGRES_USER : postgres
      POSTGRES_PAASWORD: password
      POSTGRES_DB: postgres
    volumes:
      - "db-data:/var/lib/postgresql/data"
    networks:
      - back-tier


volumes:
  db-data:

networks:
  front-tier:
  back-tier:

    ports:
      - "5432:5432"
